### ISSUE TITLE
UI using Streamlit

### ISSUE THREAD

**Issue by jeffersonzaki** [Gal-Gilor/winnie-the-pooch-detector#1]
A User Interface is needed for clients to interact with the product, the UI will be used as an MVP.
Use streamlit, which is a python library to create the MVP.

Must Haves: 
1. A user must be able to select an array of images
2. A user must be able to see the results

**Comment by Gal-Gilor** [comment]
@jeffersonzaki 

Done.

If that meets user requirements, feel free to close this issue.
